package com.jiabiango.hr.mapper;

import java.util.List;

import com.jiabiango.hr.model.Resource;

public interface ResourceMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table jbg_resource
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    int insert(Resource record);
    /** 
     * This method was generated by MyBatis Generator. This method corresponds to the database table jbg_resource
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    int insertSelective(Resource record);
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table jbg_resource
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    Resource selectByPrimaryKey(Integer id);
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table jbg_resource
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    int updateByPrimaryKeySelective(Resource record);
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table jbg_resource
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    int updateByPrimaryKey(Resource record);
    List<Resource> selectAll();
    int save(Resource record);
    int update(Resource record);
}