package com.jiabiango.hr.model;

import java.util.Date;

public class Demo {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_demo.id
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_demo.name
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_demo.title
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_demo.min
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    private Integer min;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_demo.max
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    private Integer max;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_demo.status
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    private String status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_demo.demo_time
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    private Date demoTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_demo.create_time
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_demo.id
     * @return  the value of jbg_demo.id
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_demo.id
     * @param id  the value for jbg_demo.id
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_demo.name
     * @return  the value of jbg_demo.name
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_demo.name
     * @param name  the value for jbg_demo.name
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_demo.title
     * @return  the value of jbg_demo.title
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_demo.title
     * @param title  the value for jbg_demo.title
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_demo.min
     * @return  the value of jbg_demo.min
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    public Integer getMin() {
        return min;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_demo.min
     * @param min  the value for jbg_demo.min
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    public void setMin(Integer min) {
        this.min = min;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_demo.max
     * @return  the value of jbg_demo.max
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    public Integer getMax() {
        return max;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_demo.max
     * @param max  the value for jbg_demo.max
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    public void setMax(Integer max) {
        this.max = max;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_demo.status
     * @return  the value of jbg_demo.status
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_demo.status
     * @param status  the value for jbg_demo.status
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_demo.demo_time
     * @return  the value of jbg_demo.demo_time
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    public Date getDemoTime() {
        return demoTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_demo.demo_time
     * @param demoTime  the value for jbg_demo.demo_time
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    public void setDemoTime(Date demoTime) {
        this.demoTime = demoTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_demo.create_time
     * @return  the value of jbg_demo.create_time
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_demo.create_time
     * @param createTime  the value for jbg_demo.create_time
     * @mbg.generated  Wed Feb 07 10:15:56 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}