package com.jiabiango.hr.model;

import java.util.Date;

public class Resource {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_resource.id
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_resource.name
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_resource.res_desc
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    private String resDesc;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_resource.url
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    private String url;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_resource.match_type
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    private String matchType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_resource.http_method
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    private String httpMethod;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_resource.authority
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    private String authority;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_resource.parent_id
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    private Integer parentId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_resource.type
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    private String type;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_resource.sort
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    private Integer sort;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_resource.status
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    private String status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_resource.create_by
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    private String createBy;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_resource.create_time
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_resource.update_by
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    private String updateBy;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_resource.update_time
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_resource.id
     * @return  the value of jbg_resource.id
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_resource.id
     * @param id  the value for jbg_resource.id
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_resource.name
     * @return  the value of jbg_resource.name
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_resource.name
     * @param name  the value for jbg_resource.name
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_resource.res_desc
     * @return  the value of jbg_resource.res_desc
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public String getResDesc() {
        return resDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_resource.res_desc
     * @param resDesc  the value for jbg_resource.res_desc
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public void setResDesc(String resDesc) {
        this.resDesc = resDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_resource.url
     * @return  the value of jbg_resource.url
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_resource.url
     * @param url  the value for jbg_resource.url
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_resource.match_type
     * @return  the value of jbg_resource.match_type
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public String getMatchType() {
        return matchType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_resource.match_type
     * @param matchType  the value for jbg_resource.match_type
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public void setMatchType(String matchType) {
        this.matchType = matchType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_resource.http_method
     * @return  the value of jbg_resource.http_method
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public String getHttpMethod() {
        return httpMethod;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_resource.http_method
     * @param httpMethod  the value for jbg_resource.http_method
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public void setHttpMethod(String httpMethod) {
        this.httpMethod = httpMethod;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_resource.authority
     * @return  the value of jbg_resource.authority
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public String getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_resource.authority
     * @param authority  the value for jbg_resource.authority
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public void setAuthority(String authority) {
        this.authority = authority;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_resource.parent_id
     * @return  the value of jbg_resource.parent_id
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_resource.parent_id
     * @param parentId  the value for jbg_resource.parent_id
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_resource.type
     * @return  the value of jbg_resource.type
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_resource.type
     * @param type  the value for jbg_resource.type
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_resource.sort
     * @return  the value of jbg_resource.sort
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_resource.sort
     * @param sort  the value for jbg_resource.sort
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_resource.status
     * @return  the value of jbg_resource.status
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_resource.status
     * @param status  the value for jbg_resource.status
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_resource.create_by
     * @return  the value of jbg_resource.create_by
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_resource.create_by
     * @param createBy  the value for jbg_resource.create_by
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_resource.create_time
     * @return  the value of jbg_resource.create_time
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_resource.create_time
     * @param createTime  the value for jbg_resource.create_time
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_resource.update_by
     * @return  the value of jbg_resource.update_by
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_resource.update_by
     * @param updateBy  the value for jbg_resource.update_by
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_resource.update_time
     * @return  the value of jbg_resource.update_time
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_resource.update_time
     * @param updateTime  the value for jbg_resource.update_time
     * @mbg.generated  Wed Mar 07 23:54:44 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    private String clientName;

    public String getClientName() {
        return clientName;
    }

    public void setClientName(String clientName) {
        this.clientName = clientName;
    }
}