package com.jiabiango.hr.model;

import java.util.Date;

public class RoleResource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbg_role_resource.id
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbg_role_resource.role_id
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbg_role_resource.resource_id
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    private Integer resourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbg_role_resource.status
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbg_role_resource.create_by
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbg_role_resource.create_time
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbg_role_resource.update_by
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbg_role_resource.update_time
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbg_role_resource.id
     *
     * @return the value of jbg_role_resource.id
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbg_role_resource.id
     *
     * @param id the value for jbg_role_resource.id
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbg_role_resource.role_id
     *
     * @return the value of jbg_role_resource.role_id
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbg_role_resource.role_id
     *
     * @param roleId the value for jbg_role_resource.role_id
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbg_role_resource.resource_id
     *
     * @return the value of jbg_role_resource.resource_id
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbg_role_resource.resource_id
     *
     * @param resourceId the value for jbg_role_resource.resource_id
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbg_role_resource.status
     *
     * @return the value of jbg_role_resource.status
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbg_role_resource.status
     *
     * @param status the value for jbg_role_resource.status
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbg_role_resource.create_by
     *
     * @return the value of jbg_role_resource.create_by
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbg_role_resource.create_by
     *
     * @param createBy the value for jbg_role_resource.create_by
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbg_role_resource.create_time
     *
     * @return the value of jbg_role_resource.create_time
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbg_role_resource.create_time
     *
     * @param createTime the value for jbg_role_resource.create_time
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbg_role_resource.update_by
     *
     * @return the value of jbg_role_resource.update_by
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbg_role_resource.update_by
     *
     * @param updateBy the value for jbg_role_resource.update_by
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbg_role_resource.update_time
     *
     * @return the value of jbg_role_resource.update_time
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbg_role_resource.update_time
     *
     * @param updateTime the value for jbg_role_resource.update_time
     *
     * @mbg.generated Sun Mar 04 17:45:15 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}