package com.jiabiango.hr.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class User implements Serializable{

	private static final long serialVersionUID = 5193163127913832349L;
	/**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_user.id
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_user.username
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    private String username;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_user.password
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    private String password;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_user.real_name
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    private String realName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_user.gender
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    private String gender;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_user.expire_time
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    private Date expireTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_user.status
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    private String status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_user.create_by
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    private Date createBy;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_user.create_time
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_user.update_by
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    private String updateBy;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jbg_user.update_time
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_user.id
     * @return  the value of jbg_user.id
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_user.id
     * @param id  the value for jbg_user.id
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_user.username
     * @return  the value of jbg_user.username
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_user.username
     * @param username  the value for jbg_user.username
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_user.password
     * @return  the value of jbg_user.password
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_user.password
     * @param password  the value for jbg_user.password
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_user.real_name
     * @return  the value of jbg_user.real_name
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_user.real_name
     * @param realName  the value for jbg_user.real_name
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_user.gender
     * @return  the value of jbg_user.gender
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_user.gender
     * @param gender  the value for jbg_user.gender
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_user.expire_time
     * @return  the value of jbg_user.expire_time
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_user.expire_time
     * @param expireTime  the value for jbg_user.expire_time
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_user.status
     * @return  the value of jbg_user.status
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_user.status
     * @param status  the value for jbg_user.status
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_user.create_by
     * @return  the value of jbg_user.create_by
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    public Date getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_user.create_by
     * @param createBy  the value for jbg_user.create_by
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    public void setCreateBy(Date createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_user.create_time
     * @return  the value of jbg_user.create_time
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_user.create_time
     * @param createTime  the value for jbg_user.create_time
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_user.update_by
     * @return  the value of jbg_user.update_by
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_user.update_by
     * @param updateBy  the value for jbg_user.update_by
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jbg_user.update_time
     * @return  the value of jbg_user.update_time
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jbg_user.update_time
     * @param updateTime  the value for jbg_user.update_time
     * @mbg.generated  Wed Feb 28 15:33:40 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    
    public List<Role> roles;

    public List<Role> getRoles() {
        return roles;
    }

    public void setRoles(List<Role> roles) {
        this.roles = roles;
    }
    
}