package com.jiabiango.hr.model.area;

public class AllInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.id
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private Integer id;
    
    private String position;
    
    private String quName;
    
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.xiaoshoufang
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String xiaoshoufang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.goumaifang
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String goumaifang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.goumaifangdizhi
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String goumaifangdizhi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.goumaifangdianhua
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String goumaifangdianhua;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.qu
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String qu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.pai
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String pai;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.hao
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String hao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.yanshoushijian
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String yanshoushijian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.muxingmingcheng
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String muxingmingcheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.goumufei
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String goumufei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.guanlifei
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String guanlifei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.hemufei
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String hemufei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.zongjine
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String zongjine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.jiesuanfangshi
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String jiesuanfangshi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.wangzhexingming
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String wangzhexingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.anzangshijian
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String anzangshijian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.zengjianxiangmu
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String zengjianxiangmu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.jingbanren
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String jingbanren;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.zerenren
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String zerenren;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.anzangfang
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String anzangfang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.sizhexingming1
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String sizhexingming1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.sizhexingbie1
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String sizhexingbie1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.sizheshengyu1
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String sizheshengyu1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.sizhesiyu1
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String sizhesiyu1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.sizhexingming2
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String sizhexingming2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.sizhexingbie2
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String sizhexingbie2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.sizheshengyu2
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String sizheshengyu2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.sizhesiyu2
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String sizhesiyu2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.wangzheerzixingming
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String wangzheerzixingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.wangzhennverxingming
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String wangzhennverxingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.wangzheerxixingming
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String wangzheerxixingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.wangzhenvxuxingming
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String wangzhenvxuxingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_allinfo.wangzhesunbeixingming
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    private String wangzhesunbeixingming;
    
    private String wangzhezengsunbeixingming;
    
    private String beiwenxianshi;
    
    public String getBeiwenxianshi() {
		return beiwenxianshi;
	}

	public void setBeiwenxianshi(String beiwenxianshi) {
		this.beiwenxianshi = beiwenxianshi;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.id
     *
     * @return the value of bj_allinfo.id
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.id
     *
     * @param id the value for bj_allinfo.id
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.xiaoshoufang
     *
     * @return the value of bj_allinfo.xiaoshoufang
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getXiaoshoufang() {
        return xiaoshoufang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.xiaoshoufang
     *
     * @param xiaoshoufang the value for bj_allinfo.xiaoshoufang
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setXiaoshoufang(String xiaoshoufang) {
        this.xiaoshoufang = xiaoshoufang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.goumaifang
     *
     * @return the value of bj_allinfo.goumaifang
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getGoumaifang() {
        return goumaifang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.goumaifang
     *
     * @param goumaifang the value for bj_allinfo.goumaifang
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setGoumaifang(String goumaifang) {
        this.goumaifang = goumaifang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.goumaifangdizhi
     *
     * @return the value of bj_allinfo.goumaifangdizhi
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getGoumaifangdizhi() {
        return goumaifangdizhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.goumaifangdizhi
     *
     * @param goumaifangdizhi the value for bj_allinfo.goumaifangdizhi
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setGoumaifangdizhi(String goumaifangdizhi) {
        this.goumaifangdizhi = goumaifangdizhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.goumaifangdianhua
     *
     * @return the value of bj_allinfo.goumaifangdianhua
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getGoumaifangdianhua() {
        return goumaifangdianhua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.goumaifangdianhua
     *
     * @param goumaifangdianhua the value for bj_allinfo.goumaifangdianhua
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setGoumaifangdianhua(String goumaifangdianhua) {
        this.goumaifangdianhua = goumaifangdianhua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.qu
     *
     * @return the value of bj_allinfo.qu
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getQu() {
        return qu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.qu
     *
     * @param qu the value for bj_allinfo.qu
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setQu(String qu) {
        this.qu = qu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.pai
     *
     * @return the value of bj_allinfo.pai
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getPai() {
        return pai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.pai
     *
     * @param pai the value for bj_allinfo.pai
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setPai(String pai) {
        this.pai = pai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.hao
     *
     * @return the value of bj_allinfo.hao
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getHao() {
        return hao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.hao
     *
     * @param hao the value for bj_allinfo.hao
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setHao(String hao) {
        this.hao = hao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.yanshoushijian
     *
     * @return the value of bj_allinfo.yanshoushijian
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getYanshoushijian() {
        return yanshoushijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.yanshoushijian
     *
     * @param yanshoushijian the value for bj_allinfo.yanshoushijian
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setYanshoushijian(String yanshoushijian) {
        this.yanshoushijian = yanshoushijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.muxingmingcheng
     *
     * @return the value of bj_allinfo.muxingmingcheng
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getMuxingmingcheng() {
        return muxingmingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.muxingmingcheng
     *
     * @param muxingmingcheng the value for bj_allinfo.muxingmingcheng
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setMuxingmingcheng(String muxingmingcheng) {
        this.muxingmingcheng = muxingmingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.goumufei
     *
     * @return the value of bj_allinfo.goumufei
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getGoumufei() {
        return goumufei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.goumufei
     *
     * @param goumufei the value for bj_allinfo.goumufei
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setGoumufei(String goumufei) {
        this.goumufei = goumufei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.guanlifei
     *
     * @return the value of bj_allinfo.guanlifei
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getGuanlifei() {
        return guanlifei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.guanlifei
     *
     * @param guanlifei the value for bj_allinfo.guanlifei
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setGuanlifei(String guanlifei) {
        this.guanlifei = guanlifei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.hemufei
     *
     * @return the value of bj_allinfo.hemufei
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getHemufei() {
        return hemufei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.hemufei
     *
     * @param hemufei the value for bj_allinfo.hemufei
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setHemufei(String hemufei) {
        this.hemufei = hemufei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.zongjine
     *
     * @return the value of bj_allinfo.zongjine
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getZongjine() {
        return zongjine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.zongjine
     *
     * @param zongjine the value for bj_allinfo.zongjine
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setZongjine(String zongjine) {
        this.zongjine = zongjine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.jiesuanfangshi
     *
     * @return the value of bj_allinfo.jiesuanfangshi
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getJiesuanfangshi() {
        return jiesuanfangshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.jiesuanfangshi
     *
     * @param jiesuanfangshi the value for bj_allinfo.jiesuanfangshi
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setJiesuanfangshi(String jiesuanfangshi) {
        this.jiesuanfangshi = jiesuanfangshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.wangzhexingming
     *
     * @return the value of bj_allinfo.wangzhexingming
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getWangzhexingming() {
        return wangzhexingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.wangzhexingming
     *
     * @param wangzhexingming the value for bj_allinfo.wangzhexingming
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setWangzhexingming(String wangzhexingming) {
        this.wangzhexingming = wangzhexingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.anzangshijian
     *
     * @return the value of bj_allinfo.anzangshijian
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getAnzangshijian() {
        return anzangshijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.anzangshijian
     *
     * @param anzangshijian the value for bj_allinfo.anzangshijian
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setAnzangshijian(String anzangshijian) {
        this.anzangshijian = anzangshijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.zengjianxiangmu
     *
     * @return the value of bj_allinfo.zengjianxiangmu
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getZengjianxiangmu() {
        return zengjianxiangmu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.zengjianxiangmu
     *
     * @param zengjianxiangmu the value for bj_allinfo.zengjianxiangmu
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setZengjianxiangmu(String zengjianxiangmu) {
        this.zengjianxiangmu = zengjianxiangmu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.jingbanren
     *
     * @return the value of bj_allinfo.jingbanren
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getJingbanren() {
        return jingbanren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.jingbanren
     *
     * @param jingbanren the value for bj_allinfo.jingbanren
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setJingbanren(String jingbanren) {
        this.jingbanren = jingbanren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.zerenren
     *
     * @return the value of bj_allinfo.zerenren
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getZerenren() {
        return zerenren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.zerenren
     *
     * @param zerenren the value for bj_allinfo.zerenren
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setZerenren(String zerenren) {
        this.zerenren = zerenren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.anzangfang
     *
     * @return the value of bj_allinfo.anzangfang
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getAnzangfang() {
        return anzangfang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.anzangfang
     *
     * @param anzangfang the value for bj_allinfo.anzangfang
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setAnzangfang(String anzangfang) {
        this.anzangfang = anzangfang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.sizhexingming1
     *
     * @return the value of bj_allinfo.sizhexingming1
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getSizhexingming1() {
        return sizhexingming1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.sizhexingming1
     *
     * @param sizhexingming1 the value for bj_allinfo.sizhexingming1
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setSizhexingming1(String sizhexingming1) {
        this.sizhexingming1 = sizhexingming1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.sizhexingbie1
     *
     * @return the value of bj_allinfo.sizhexingbie1
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getSizhexingbie1() {
        return sizhexingbie1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.sizhexingbie1
     *
     * @param sizhexingbie1 the value for bj_allinfo.sizhexingbie1
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setSizhexingbie1(String sizhexingbie1) {
        this.sizhexingbie1 = sizhexingbie1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.sizheshengyu1
     *
     * @return the value of bj_allinfo.sizheshengyu1
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getSizheshengyu1() {
        return sizheshengyu1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.sizheshengyu1
     *
     * @param sizheshengyu1 the value for bj_allinfo.sizheshengyu1
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setSizheshengyu1(String sizheshengyu1) {
        this.sizheshengyu1 = sizheshengyu1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.sizhesiyu1
     *
     * @return the value of bj_allinfo.sizhesiyu1
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getSizhesiyu1() {
        return sizhesiyu1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.sizhesiyu1
     *
     * @param sizhesiyu1 the value for bj_allinfo.sizhesiyu1
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setSizhesiyu1(String sizhesiyu1) {
        this.sizhesiyu1 = sizhesiyu1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.sizhexingming2
     *
     * @return the value of bj_allinfo.sizhexingming2
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getSizhexingming2() {
        return sizhexingming2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.sizhexingming2
     *
     * @param sizhexingming2 the value for bj_allinfo.sizhexingming2
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setSizhexingming2(String sizhexingming2) {
        this.sizhexingming2 = sizhexingming2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.sizhexingbie2
     *
     * @return the value of bj_allinfo.sizhexingbie2
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getSizhexingbie2() {
        return sizhexingbie2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.sizhexingbie2
     *
     * @param sizhexingbie2 the value for bj_allinfo.sizhexingbie2
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setSizhexingbie2(String sizhexingbie2) {
        this.sizhexingbie2 = sizhexingbie2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.sizheshengyu2
     *
     * @return the value of bj_allinfo.sizheshengyu2
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getSizheshengyu2() {
        return sizheshengyu2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.sizheshengyu2
     *
     * @param sizheshengyu2 the value for bj_allinfo.sizheshengyu2
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setSizheshengyu2(String sizheshengyu2) {
        this.sizheshengyu2 = sizheshengyu2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.sizhesiyu2
     *
     * @return the value of bj_allinfo.sizhesiyu2
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getSizhesiyu2() {
        return sizhesiyu2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.sizhesiyu2
     *
     * @param sizhesiyu2 the value for bj_allinfo.sizhesiyu2
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setSizhesiyu2(String sizhesiyu2) {
        this.sizhesiyu2 = sizhesiyu2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.wangzheerzixingming
     *
     * @return the value of bj_allinfo.wangzheerzixingming
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getWangzheerzixingming() {
        return wangzheerzixingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.wangzheerzixingming
     *
     * @param wangzheerzixingming the value for bj_allinfo.wangzheerzixingming
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setWangzheerzixingming(String wangzheerzixingming) {
        this.wangzheerzixingming = wangzheerzixingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.wangzhennverxingming
     *
     * @return the value of bj_allinfo.wangzhennverxingming
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getWangzhennverxingming() {
        return wangzhennverxingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.wangzhennverxingming
     *
     * @param wangzhennverxingming the value for bj_allinfo.wangzhennverxingming
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setWangzhennverxingming(String wangzhennverxingming) {
        this.wangzhennverxingming = wangzhennverxingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.wangzheerxixingming
     *
     * @return the value of bj_allinfo.wangzheerxixingming
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getWangzheerxixingming() {
        return wangzheerxixingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.wangzheerxixingming
     *
     * @param wangzheerxixingming the value for bj_allinfo.wangzheerxixingming
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setWangzheerxixingming(String wangzheerxixingming) {
        this.wangzheerxixingming = wangzheerxixingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.wangzhenvxuxingming
     *
     * @return the value of bj_allinfo.wangzhenvxuxingming
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getWangzhenvxuxingming() {
        return wangzhenvxuxingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.wangzhenvxuxingming
     *
     * @param wangzhenvxuxingming the value for bj_allinfo.wangzhenvxuxingming
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setWangzhenvxuxingming(String wangzhenvxuxingming) {
        this.wangzhenvxuxingming = wangzhenvxuxingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_allinfo.wangzhesunbeixingming
     *
     * @return the value of bj_allinfo.wangzhesunbeixingming
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public String getWangzhesunbeixingming() {
        return wangzhesunbeixingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_allinfo.wangzhesunbeixingming
     *
     * @param wangzhesunbeixingming the value for bj_allinfo.wangzhesunbeixingming
     *
     * @mbggenerated Sat Apr 20 20:00:10 CST 2019
     */
    public void setWangzhesunbeixingming(String wangzhesunbeixingming) {
        this.wangzhesunbeixingming = wangzhesunbeixingming;
    }

	public String getPosition() {
		return position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getQuName() {
		return quName;
	}

	public void setQuName(String quName) {
		this.quName = quName;
	}

	public String getWangzhezengsunbeixingming() {
		return wangzhezengsunbeixingming;
	}

	public void setWangzhezengsunbeixingming(String wangzhezengsunbeixingming) {
		this.wangzhezengsunbeixingming = wangzhezengsunbeixingming;
	}
	
	
    
}