package com.jiabiango.hr.model.area;

public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_area.id
     *
     * @mbggenerated Tue Apr 16 21:15:48 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bj_area.name
     *
     * @mbggenerated Tue Apr 16 21:15:48 CST 2019
     */
    private String name;

    private Integer type;
    
    private Integer sortNum;
    
    private String [] allLie;

    public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_area.id
     *
     * @return the value of bj_area.id
     *
     * @mbggenerated Tue Apr 16 21:15:48 CST 2019
     */
    
    
    
    
    
    
    public Integer getId() {
        return id;
    }

  

 



	public Integer getSortNum() {
		return sortNum;
	}







	public void setSortNum(Integer sortNum) {
		this.sortNum = sortNum;
	}






 

	public String[] getAllLie() {
		return allLie;
	}







	public void setAllLie(String[] allLie) {
		this.allLie = allLie;
	}







	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_area.id
     *
     * @param id the value for bj_area.id
     *
     * @mbggenerated Tue Apr 16 21:15:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bj_area.name
     *
     * @return the value of bj_area.name
     *
     * @mbggenerated Tue Apr 16 21:15:48 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bj_area.name
     *
     * @param name the value for bj_area.name
     *
     * @mbggenerated Tue Apr 16 21:15:48 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

  
}